version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: academy-quiz-app
    container_name: academy-quiz-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "9000:9000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_DATABASE=quiz_system
      - DB_USERNAME=root
      - DB_PASSWORD=secret

  db:
    image: mysql:8.0
    container_name: academy-quiz-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: quiz_system
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
